### ISSUE TITLE
info scale

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsdmvn#12]
For `gs_power_npe()`, we will add an additional argument called `info_scale`:
`2`: default: do calculations as currently specified. Since this is default, all will be backwards compatible.
`0`: use null hypothesis info0 for all calculations
`1`: use alternate hypothesis info1 for all calculations

By re-developping `gs_power_npe()`, the following functions would also be impacted: `gs_design_npe()`, `gs_power_ahr()`, `gs_design_ahr()`, `gs_power_wlr()`, `gs_design_wlr()`.
However, these would all pass `info_scale` to `gs_power_npe()` which is the calculation engine for all of them; this needs to be reviewed and verified as maybe `gs_design_npe()` will also need some non-trivial work done. 
We would NOT change any of the `gs_info_xx()` functions.

**Comment by nanxstats** [comment]
From the grammar side, it would be great if we can use enumerate all possible options for the argument as characters (which probably also require **better naming for the options**) instead of using a single integer. This is discussed in <https://design.tidyverse.org/def-enum.html>.

You cannot enumerate an integer-based argument:

```r
f <- function (x = c(2, 0, 1)) {
  x <- match.arg(x)
  x
}

f()
#> Error in match.arg(x) : 'arg' must be NULL or a character vector
```

but can enumerate a character-based argument:

```r
g <- function (x = c("2", "0", "1")) {
  x <- match.arg(x)
  x
}

g()

#> [1] "2"
```
