### ISSUE TITLE
`gs_power_wlr` default error

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsdmvn#22]
The following code uses the default arguments in `gs_power_wlr`. And we have an error here.
```
gs_power_wlr(
  enrollRates = tibble::tibble(Stratum = "All", duration = c(2, 2, 10), rate = c(3, 6,
                                                                                 9)),
  failRates = tibble::tibble(Stratum = "All", duration = c(3, 100), failRate =
                               log(2)/c(9, 18), hr = c(0.9, 0.6), dropoutRate = rep(0.001, 2)),
  ratio = 1,
  weight = wlr_weight_fh,
  approx = "asymptotic",
  events = c(30, 40, 50),
  analysisTimes = NULL,
  binding = FALSE,
  upper = gs_b,
  upar = gsDesign(k = length(events), test.type = 1, n.I = events, maxn.IPlan =
                    max(events), sfu = sfLDOF, sfupar = NULL)$upper$bound,
  lower = gs_b,
  lpar = c(qnorm(0.1), rep(-Inf, length(events) - 1)),
  test_upper = TRUE,
  test_lower = TRUE,
  r = 18,
  tol = 1e-06
)
```

Error message: 
```
Error in lower(k = k, par = lpar, hgm1 = hgm1_1, theta = theta1, info = info1,  :  object 'events' not found
```

**Comment by elong0527** [comment]
It is not a bug, the issue is the proper use of default value. 

You can either call
```
gs_power_wlr()
```

or

```
events <- c(30, 40, 50)
gs_power_wlr(
  enrollRates = tibble::tibble(Stratum = "All", duration = c(2, 2, 10), rate = c(3, 6,
                                                                                 9)),
  failRates = tibble::tibble(Stratum = "All", duration = c(3, 100), failRate =
                               log(2)/c(9, 18), hr = c(0.9, 0.6), dropoutRate = rep(0.001, 2)),
  ratio = 1,
  weight = wlr_weight_fh,
  approx = "asymptotic",
  events = events,
  analysisTimes = NULL,
  binding = FALSE,
  upper = gs_b,
  upar = gsDesign(k = length(events), test.type = 1, n.I = events, maxn.IPlan =
                    max(events), sfu = sfLDOF, sfupar = NULL)$upper$bound,
  lower = gs_b,
  lpar = c(qnorm(0.1), rep(-Inf, length(events) - 1)),
  test_upper = TRUE,
  test_lower = TRUE,
  r = 18,
  tol = 1e-06
)
```

The way you are calling the function require `events` to be defined in the global environment. The way the default argument works for `upar` is to look `events` defined in function argument.  

It is also a good reason we need to refactor the function input to avoid dependency of input. 

cc: @nanxstats

**Comment by elong0527** [comment]
Here is a minimal reproducible example to illustrate the idea.

```
x <- function(a = 1, b = length(a)){
  return(b)
}

# Works 
x()

# Not working as `a` is not defined in global environment. 
x(a = 1, b = length(a))
```

**Comment by nanxstats** [comment]
I agree. Besides `events`, I would also encourage writing that `gsDesign()` call outside this `gs_power_wlr()` call and pass in the value so that the evaluation scope is clear.

On argument dependency, as we mentioned before, it would be ideal to have a dedicated class of objects (a package) to represent the spending functions (or bounds in general) like in [scales](https://scales.r-lib.org/reference/) to avoid inter-dependent arguments like `upper` and `upar`.

On managing input parameter lifecycle, [dials](https://dials.tidymodels.org/) has some good ideas on systematically composing, validating, and finalizing a large number of parameters, so that the input of `gs_power_wlr()` will become much simpler - for example, one argument `param` (and maybe some special additions). This will also make those parameters reusable in other similar functions.
